### ISSUE TITLE
Iterate on print styles

### ISSUE THREAD

**Issue by jpadilla** [codeforct/wp-amplify-legislator-database#4]
We should tweak generated table and print styles to match the existing documents as much as possible.

![CAC 15 Legislators With Contact  Info 2019 (1)-1 (dragged)](https://user-images.githubusercontent.com/83319/70534037-3892ad80-1b28-11ea-99b8-caf5c5cffd66.png)

[CAC 15 Legislators With Contact  Info 2019 (1).pdf](https://github.com/codeforct/wp-amplify-legislator-database/files/3945063/CAC.15.Legislators.With.Contact.Info.2019.1.pdf)

**Comment by ericabodden** [comment]
![Amplify Thumbnail Logo](https://user-images.githubusercontent.com/53189321/70744522-d84e6800-1cef-11ea-8368-249e4aa02e5c.jpg)
The client went through a merger this past year and now operates under Amplify, Inc. For the purposes of this doc, please use the attached logo thumbnail and not the full logo. I'd like to leave out the address as they may be moving in the future. The phone number is the same. The new contact email is info@amplifyct.org. The new website address will be www.amplifyct.org. I've included the full logo so that we can match the color and font. 
![Amplify Full Logo](https://user-images.githubusercontent.com/53189321/70744745-590d6400-1cf0-11ea-99bb-66931d42ddbc.jpg)
